[project]
name = "speeder"
version = "1.2.1"
description = "Python script to monitor your internet speed! ðŸš€"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.49.0",
    "loguru>=0.7.3",
]
